### ISSUE TITLE
make .git folder location configurable

### ISSUE THREAD

**Issue by allanbowe** [peacechen/node-git-hooks#3]
In my customer project, the `package.json` is not in the root.  This is actually because the git repository contains two projects.

Due to this, the install fails with the following message:

![image](https://user-images.githubusercontent.com/4420615/111967936-e8f7ab80-8af8-11eb-8f67-5d2819e0429f.png)

> The installation isn't a GIT repo.  Skipping hooks installation.

Would it be possible to configure `node-git-hooks` so that the (relative) location of the .git folder can be provided?

**Comment by peacechen** [comment]
A flag could be added to package.json to control whether node-git-hooks checks for a .git folder. Would you mind submitting a PR?

**Comment by peacechen** [comment]
This has been published in 1.0.6.  Note that if you have multiple projects in a repo, they'll all use the same git hooks since there's only one `.git` folder. Correspondingly, if you set up node-git-hooks in multiple sub-folders, they will overwrite each others' git hooks.

https://github.com/peacechen/node-git-hooks#advanced-usage
